CodeSystem: BreastLocationRegionCS
Title: "Breast Location Region CodeSystem"
Description: "Breast body location region code system."
  * #Axilla "Axilla"
  * #AxillaryTail "Axillary tail"
  * #AxillaI "Axilla I"
  * #AxillaII "Axilla II"
  * #AxillaIII "Axilla III"
  * #InframammaryFold "Inframammary fold"
  * #InSkin "In skin"
  * #CentralToNipple "Central to nipple"